services:
  app:
    image: golang:1.25-bookworm
    working_dir: /app
    volumes:
      - .:/app
      - ./storage:/app/storage
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    command: sh -c "apt-get update && apt-get install -y ffmpeg && tail -f /dev/null"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"